### PR TITLE
Rc bug fixing

### LINKED ISSUE #116: Find command doesn't accept name keywords that contain spaces
fix this

### LINKED ISSUE #174: [PE-D] Index larger than MAX_INT or smaller than MIN_INT
For commands with an index field (eg delete, status...), inputting an integer smaller than MIN_INT or larger than MAX_INT gives an "invalid command format" message rather than an "invalid index" message.

Similarly, for commands with an episode field (add, update), having an input larger than MAX_INT results in the user not being able to enter the command line.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: fullfatwasabi/ped#5

### LINKED ISSUE #175: [PE-D] Anime name is not displayed properly
The last line of the anime name is partially blocked if the name is too long.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ngchisern/ped#8

### PR DESCRIPTION
**Pull request by NekrozQliphort**
Fix #175 
Fix #174 
Fix #116

### CODE REVIEW

File: src/main/java/seedu/anilist/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -29,9 +30,13 @@
      */
     public static Index parseIndex(String oneBasedIndex) throws ParseException {
         String trimmedIndex = oneBasedIndex.trim();
-        if (!StringUtil.isNonZeroUnsignedInteger(trimmedIndex)) {
+        if (!StringUtil.isValidNumber(trimmedIndex)) {
             throw new ParseException(MESSAGE_INVALID_INDEX);
         }
+
+        if (!StringUtil.isNonZeroUnsignedInteger(trimmedIndex)) {
+            throw new IntegerOutOfRangeException(1, Integer.MAX_VALUE);
```
Comment (muhammad-faruq) [inline src/main/java/seedu/anilist/logic/parser/ParserUtil.java:38]: uhh why does IntegerOutOfRangeException take in 1 and maxint as its parameters? is this necessary?

File: src/test/java/seedu/anilist/logic/parser/FindCommandParserTest.java [hunk 2]
```diff
@@ -9,6 +9,8 @@
 
 import seedu.anilist.logic.commands.FindCommand;
 import seedu.anilist.logic.parser.exceptions.ParseException;
+import seedu.anilist.model.anime.Name;
+import seedu.anilist.model.genre.Genre;
```
Comment (muhammad-faruq) [inline src/test/java/seedu/anilist/logic/parser/FindCommandParserTest.java:13]: If we are just using the messages would it be better to just import the messages themselves rather than the class?

File: src/test/java/seedu/anilist/logic/parser/RenameCommandParserTest.java [hunk 3]
```diff
@@ -36,11 +37,9 @@ public void parse_missingParts_failure() {
 
     @Test
     public void parse_invalidPreamble_failure() {
-        // negative index
-        assertParseFailure(parser, "-5" + NAME_DESC_AKIRA, MESSAGE_INVALID_FORMAT);
-
-        // zero index
-        assertParseFailure(parser, "0" + NAME_DESC_AKIRA, MESSAGE_INVALID_FORMAT);
+        // not a valid number
+        assertParseFailure(parser, "3.141582653" + NAME_DESC_AKIRA, MESSAGE_INVALID_FORMAT);
```
Comment (muhammad-faruq) [inline src/test/java/seedu/anilist/logic/parser/RenameCommandParserTest.java:41]: 3.1415926535 is rounded off to 3.141592654

**Review by muhammad-faruq — CHANGES_REQUESTED** [review]
LGTM but some small changes

File: src/main/java/seedu/anilist/commons/util/StringUtil.java [hunk 4]
```diff
@@ -65,4 +75,25 @@ public static boolean isNonZeroUnsignedInteger(String s) {
...
     }
+
+    /**
+     * Returns true if {@code s} represents an unsigned integer
+     * e.g. 0, 1, 2, 3, ..., {@code Integer.MAX_VALUE} <br>
+     * Will return false for any other non-null string input
+     * e.g. empty string, "-1", "+1", and " 2 " (untrimmed), "3 0" (contains whitespace), "1 a" (contains letters)
+     * @throws NullPointerException if {@code s} is null.
+     */
+    public static boolean isUnsignedInteger(String s) {
```
[the remark this answers is not in the document]
Comment (NekrozQliphort) [reply src/main/java/seedu/anilist/commons/util/StringUtil.java:86]: Ah here it means `Integer.parseInt(s)` works with `-1` and `+1`. However with negative numbers we check whether it is >= 0 so negative numbers don't work. Whereas we also check `!s.startsWith("+")` to make sure it's not something like `+1` (shouldnt start with "+").

Overall the function do not allow these inputs.

File: src/main/java/seedu/anilist/logic/commands/DeleteCommand.java [hunk 5]
```diff
@@ -37,7 +37,7 @@ public CommandResult execute(Model model) throws CommandException {
         List<Anime> lastShownList = model.getFilteredAnimeList();
 
         if (targetIndex.getZeroBased() >= lastShownList.size()) {
-            throw new CommandException(Messages.MESSAGE_INVALID_ANIME_DISPLAYED_INDEX);
+            throw new CommandException(Messages.MESSAGE_OUT_OF_RANGE_INDEX);
```
[the remark this answers is not in the document]
Comment (NekrozQliphort) [reply src/main/java/seedu/anilist/logic/commands/DeleteCommand.java:40]: Will do but in this case the message I believe might be different for integer overflow and just exceeding the length.

File: src/main/java/seedu/anilist/logic/parser/ParserUtil.java (hunk 1 above)
Comment (NekrozQliphort) [reply src/main/java/seedu/anilist/logic/parser/ParserUtil.java:38]: Not exactly, I made it support any range from before, so I can modify it if I just want 1-99999 for example, but I'm not too sure if it's a good idea.

File: src/test/java/seedu/anilist/logic/parser/RenameCommandParserTest.java (hunk 3 above)
Comment (NekrozQliphort) [reply src/test/java/seedu/anilist/logic/parser/RenameCommandParserTest.java:41]: Fair enough lol

File: src/test/java/seedu/anilist/logic/parser/FindCommandParserTest.java (hunk 2 above)
Comment (NekrozQliphort) [reply src/test/java/seedu/anilist/logic/parser/FindCommandParserTest.java:13]: Yes, will change that.

File: src/main/java/seedu/anilist/model/anime/Name.java [hunk 6]
```diff
@@ -10,8 +10,9 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain ASCII characters and spaces, and it should not be blank";
-
+        "Names should only contain ASCII characters and spaces, and it should have a length "
+        + "between 1 to 140 characters (not including trailing whitespaces)";
+    public static final int MAX_LEN = 140;
```
[the remark this answers is not in the document]
Comment (NekrozQliphort) [reply src/main/java/seedu/anilist/model/anime/Name.java:15]: I just checked for the maximum length for anime names, I believe it's 108, so I just upped it to the same as twitter original tweet character count.

File: src/test/java/seedu/anilist/logic/parser/FindCommandParserTest.java (hunk 2 above)
Comment (muhammad-faruq) [reply src/test/java/seedu/anilist/logic/parser/FindCommandParserTest.java:15]: oh right i didnt realize that they had the same name..

**Review by muhammad-faruq — APPROVED** [review]
lgtm
